/**
 * YouTube Video Management with Vercel KV
 * Handles categorized video library with transcripts
 * Updated: Bilingual support (EN/VI)
 */

import { kv } from '@vercel/kv'
import { Innertube } from 'youtubei.js'
import axios from 'axios'
import { trySupadataTranscriptFallback } from './supadataTranscript'

export type VideoCategory = 'Leadership' | 'AI Works' | 'Health' | 'Entertaining' | 'Human Philosophy'

/**
 * Language-specific video content
 */
export interface VideoContent {
  title: string
  description: string
  transcript?: string
  summary?: string
}

/**
 * Translation metadata
 */
export interface TranslationStatus {
  viTranslated: boolean
  translatedAt?: number
  translatedBy?: string
  translationMethod?: 'manual' | 'auto' | 'hybrid'
}

export type TranscriptStatus =
  | 'pending'
  | 'ready'
  | 'no_captions'
  | 'blocked'
  | 'failed'

export type TranscriptFailureCode =
  | 'NO_CAPTIONS'
  | 'RATE_LIMITED'
  | 'BLOCKED'
  | 'UPSTREAM_ERROR'

export type TranscriptFetchResult =
  | {
      ok: true
      transcript: string
      language?: string
      source: 'caption-track' | 'legacy-panel' | 'supadata-native'
    }
  | {
      ok: false
      code: TranscriptFailureCode
      retryable: boolean
      message: string
    }

export function transcriptStatusFromFailure(
  code: TranscriptFailureCode
): TranscriptStatus {
  if (code === 'NO_CAPTIONS') return 'no_captions'
  if (code === 'RATE_LIMITED' || code === 'BLOCKED') return 'blocked'
  return 'failed'
}

/**
 * Video interface with bilingual support
 */
export interface Video {
  id: string
  videoId: string

  // Language-agnostic metadata
  channelTitle: string
  publishedAt: string
  thumbnailUrl: string
  duration: string
  category: VideoCategory

  // Bilingual content
  en: VideoContent
  vi: VideoContent

  // Metadata
  addedAt: number
  addedBy: string
  pineconeIds?: string[]
  transcriptStatus?: TranscriptStatus
  transcriptErrorCode?: string
  translationStatus?: TranslationStatus

  // Legacy fields (for backward compatibility during migration)
  title?: string
  description?: string
  transcript?: string
  summary?: string
}

/**
 * Normalize video to bilingual format
 * Handles backward compatibility for legacy videos
 */
export function normalizeVideo(video: any): Video {
  // If already in new format, return as-is
  if (video.en && video.vi) {
    return video as Video
  }

  // Convert legacy format to new format
  return {
    ...video,
    en: {
      title: video.title || video.en?.title || '',
      description: video.description || video.en?.description || '',
      transcript: video.transcript || video.en?.transcript,
      summary: video.summary || video.en?.summary,
    },
    vi: video.vi || {
      title: '',
      description: '',
      transcript: undefined,
      summary: undefined,
    },
    translationStatus: video.translationStatus || {
      viTranslated: false,
    },
  }
}

/**
 * Extract video ID from YouTube URL
 */
export function extractVideoId(url: string): string | null {
  const patterns = [
    /(?:youtube\.com\/watch\?v=|youtu\.be\/)([^&\n?#]+)/,
    /youtube\.com\/embed\/([^&\n?#]+)/,
  ]

  for (const pattern of patterns) {
    const match = url.match(pattern)
    if (match) return match[1]
  }

  return null
}

/**
 * Get video metadata from YouTube Data API
 */
export async function getVideoMetadata(videoId: string) {
  const apiKey = process.env.YOUTUBE_API_KEY

  if (!apiKey) {
    throw new Error('YouTube API key not configured')
  }

  const response = await axios.get(
    `https://www.googleapis.com/youtube/v3/videos?part=snippet,contentDetails&id=${videoId}&key=${apiKey}`
  )

  const video = response.data.items?.[0]

  if (!video) {
    throw new Error('Video not found')
  }

  return {
    videoId,
    title: video.snippet.title,
    channelTitle: video.snippet.channelTitle,
    description: video.snippet.description,
    publishedAt: video.snippet.publishedAt,
    thumbnailUrl: video.snippet.thumbnails.medium.url,
    duration: video.contentDetails.duration,
  }
}

/**
 * Pick the best caption track for embedding: prefer manual English,
 * then auto-generated English, then any manual track (usually the video's
 * original language), then whatever is left.
 */
function pickCaptionTrack(tracks: any[] | undefined): any | null {
  if (!tracks || tracks.length === 0) return null

  const isAutoGenerated = (t: any) => t.vss_id?.startsWith('a.') || t.kind === 'asr'
  const english = tracks.filter((t: any) => t.language_code?.startsWith('en'))

  return (
    english.find((t: any) => !isAutoGenerated(t)) ||
    english[0] ||
    tracks.find((t: any) => !isAutoGenerated(t)) ||
    tracks[0]
  )
}

/**
 * Download a caption track directly via its timedtext URL (json3 format).
 */
async function fetchTranscriptFromCaptionTrack(
  info: any,
  videoId: string
): Promise<TranscriptFetchResult> {
  const track = pickCaptionTrack(info.captions?.caption_tracks)

  if (!track?.base_url) {
    console.log(`[VideoManager] No caption tracks available for ${videoId}`)
    return {
      ok: false,
      code: 'NO_CAPTIONS',
      retryable: false,
      message: 'No caption tracks are available for this video.',
    }
  }

  const url = track.base_url + (track.base_url.includes('?') ? '&' : '?') + 'fmt=json3'
  const res = await fetch(url, { signal: AbortSignal.timeout(15_000) })

  if (!res.ok) {
    console.warn(`[VideoManager] timedtext request failed for ${videoId}: HTTP ${res.status}`)
    const rateLimited = res.status === 429
    const blocked = res.status === 403
    return {
      ok: false,
      code: rateLimited ? 'RATE_LIMITED' : blocked ? 'BLOCKED' : 'UPSTREAM_ERROR',
      retryable: rateLimited || blocked || res.status >= 500,
      message: `YouTube caption request failed with HTTP ${res.status}.`,
    }
  }

  // YouTube soft-blocks unauthorized sessions with an HTTP 200 + empty body
  const body = await res.text()
  if (!body) {
    console.warn(`[VideoManager] timedtext returned empty body for ${videoId} (session likely blocked)`)
    return {
      ok: false,
      code: 'BLOCKED',
      retryable: true,
      message: 'YouTube returned an empty caption response.',
    }
  }

  let data: any
  try {
    data = JSON.parse(body)
  } catch {
    return {
      ok: false,
      code: 'UPSTREAM_ERROR',
      retryable: true,
      message: 'YouTube returned an invalid caption response.',
    }
  }
  const fullText = (data.events || [])
    .flatMap((event: any) => (event.segs || []).map((seg: any) => seg.utf8 || ''))
    .join('')
    .replace(/\s+/g, ' ')
    .trim()

  if (fullText) {
    console.log(
      `[VideoManager] Fetched transcript for ${videoId} via caption track "${track.language_code}": ${fullText.split(/\s+/).length} words`
    )
  }

  if (!fullText) {
    return {
      ok: false,
      code: 'UPSTREAM_ERROR',
      retryable: true,
      message: 'YouTube returned a caption track with no usable text.',
    }
  }

  return {
    ok: true,
    transcript: fullText,
    language: track.language_code,
    source: 'caption-track',
  }
}

/**
 * Get video transcript using youtubei.js
 */
export async function getVideoTranscriptResult(
  videoId: string
): Promise<TranscriptFetchResult> {
  try {
    // generate_session_locally is required: without it YouTube soft-blocks
    // caption downloads (HTTP 200 with an empty body)
    const youtube = await Innertube.create({ generate_session_locally: true })
    const info = await youtube.getInfo(videoId)

    // Primary: download the caption track directly. YouTube's get_transcript
    // endpoint (used by info.getTranscript below) started returning HTTP 400
    // around early 2026, which silently dropped transcripts for new videos.
    const fromTrack = await fetchTranscriptFromCaptionTrack(info, videoId)
    if (fromTrack.ok) return fromTrack

    // Fallback: legacy transcript panel endpoint
    try {
      const transcriptData = await info.getTranscript()

      if (transcriptData?.transcript?.content?.body?.initial_segments) {
        const segments = transcriptData.transcript.content.body.initial_segments
        const fullText = segments.map((seg: any) => seg.snippet.text).join(' ')
        console.log(`[VideoManager] Fetched transcript for ${videoId}: ${segments.length} segments, ${fullText.split(/\s+/).length} words`)
        return {
          ok: true,
          transcript: fullText,
          source: 'legacy-panel',
        }
      }
    } catch (error: any) {
      console.warn(
        `[VideoManager] Legacy transcript fallback failed for ${videoId}:`,
        error.message
      )
    }

    console.warn(
      `[VideoManager] ⚠️ Transcript unavailable for ${videoId}: ${fromTrack.code}`
    )
    return await trySupadataTranscriptFallback({
      videoId,
      primaryResult: fromTrack,
    })
  } catch (error: any) {
    console.error(`[VideoManager] ⚠️ Failed to get transcript for ${videoId} — video will be saved without transcript:`, error.message)
    const message = String(error?.message || '')
    const rateLimited = /\b429\b|rate.?limit/i.test(message)
    const blocked = /\b403\b|forbidden|blocked/i.test(message)
    const primaryResult: TranscriptFetchResult = {
      ok: false,
      code: rateLimited ? 'RATE_LIMITED' : blocked ? 'BLOCKED' : 'UPSTREAM_ERROR',
      retryable: true,
      message: rateLimited
        ? 'YouTube rate-limited the transcript request.'
        : blocked
          ? 'YouTube blocked the transcript request.'
          : 'YouTube transcript request failed.',
    }
    return await trySupadataTranscriptFallback({
      videoId,
      primaryResult,
    })
  }
}

/** Backward-compatible string API for existing callers. */
export async function getVideoTranscript(videoId: string): Promise<string> {
  const result = await getVideoTranscriptResult(videoId)
  return result.ok ? result.transcript : ''
}

/**
 * Save video to Vercel KV
 */
export async function saveVideo(video: Video): Promise<void> {
  try {
    const key = `video:${video.id}`
    await kv.set(key, video)

    // Add to category list
    await kv.sadd(`videos:${video.category}`, video.id)

    // Add to all videos sorted set (by added date)
    await kv.zadd('videos:all', { score: video.addedAt, member: video.id })
  } catch (error) {
    console.error('Failed to save video:', error)
    throw new Error('Failed to save video')
  }
}

/**
 * Get video by ID
 */
export async function getVideo(videoId: string): Promise<Video | null> {
  try {
    const video = await kv.get<any>(`video:${videoId}`)
    if (!video) return null

    // Normalize to ensure bilingual format
    return normalizeVideo(video)
  } catch (error) {
    console.error('Failed to get video:', error)
    return null
  }
}

/**
 * Get videos by category
 */
export async function getVideosByCategory(category: VideoCategory): Promise<Video[]> {
  try {
    const videoIds = await kv.smembers(`videos:${category}`)
    const videos: Video[] = []

    for (const id of videoIds) {
      const video = await getVideo(id as string)
      if (video) {
        videos.push(video)
      }
    }

    // Sort by added date (newest first)
    return videos.sort((a, b) => b.addedAt - a.addedAt)
  } catch (error) {
    console.error('Failed to get videos by category:', error)
    return []
  }
}

/**
 * Get all videos (paginated)
 */
export async function getAllVideos(limit: number = 50, offset: number = 0): Promise<Video[]> {
  try {
    const videoIds = await kv.zrange('videos:all', offset, offset + limit - 1, { rev: true })
    const videos: Video[] = []

    for (const id of videoIds) {
      const video = await getVideo(id as string)
      if (video) {
        videos.push(video)
      }
    }

    return videos
  } catch (error) {
    console.error('Failed to get all videos:', error)
    return []
  }
}

/**
 * Update video category with atomic-like operations
 */
export async function updateVideoCategory(videoId: string, newCategory: VideoCategory): Promise<void> {
  const video = await getVideo(videoId)
  if (!video) {
    throw new Error('Video not found')
  }

  const oldCategory = video.category

  // No change needed
  if (oldCategory === newCategory) {
    console.log(`[VideoManager] Video ${videoId} already in category ${newCategory}`)
    return
  }

  console.log(`[VideoManager] Moving video ${videoId} from ${oldCategory} to ${newCategory}`)

  // Step 1: Update video object
  const updatedVideo = { ...video, category: newCategory }
  await kv.set(`video:${videoId}`, updatedVideo)

  // Step 2: Update category sets with Promise.allSettled
  const categoryOperations = [
    kv.srem(`videos:${oldCategory}`, videoId),
    kv.sadd(`videos:${newCategory}`, videoId),
  ]

  const results = await Promise.allSettled(categoryOperations)
  const failures = results.filter(r => r.status === 'rejected')

  if (failures.length > 0) {
    console.error('[VideoManager] Partial category update failure:', failures)

    // Rollback video object update
    try {
      await kv.set(`video:${videoId}`, video)
      console.log('[VideoManager] Rolled back video object update')
    } catch (rollbackError) {
      console.error('[VideoManager] Failed to rollback video update:', rollbackError)
    }

    throw new Error(`Failed to update category sets. ${failures.length}/2 operations failed. Changes rolled back. Run rebuild stats to fix any inconsistencies.`)
  }

  console.log(`[VideoManager] Successfully moved video ${videoId} to ${newCategory}`)
}

/**
 * Delete video with atomic-like operations and cleanup
 */
export async function deleteVideo(videoId: string): Promise<{ deletedVectorIds: string[] }> {
  const video = await getVideo(videoId)
  if (!video) {
    throw new Error('Video not found')
  }

  console.log(`[VideoManager] Deleting video ${videoId} from category ${video.category}`)

  // Step 1: Delete every Pinecone vector for this video. This is blocking on
  // purpose: if cleanup fails, keep the KV record so the admin can retry
  // instead of creating permanent, untraceable orphan vectors.
  const { deleteVideoVectors } = await import('./pinecone')
  const deletedVectorIds = await deleteVideoVectors(
    video.videoId,
    video.pineconeIds || []
  )
  console.log(
    `[VideoManager] Requested deletion of ${deletedVectorIds.length} Pinecone vectors`
  )

  // Step 2: Delete from KV with Promise.allSettled to track failures
  const kvOperations = [
    kv.del(`video:${videoId}`),
    kv.srem(`videos:${video.category}`, videoId),
    kv.zrem('videos:all', videoId),
  ]

  const results = await Promise.allSettled(kvOperations)

  // Check for failures
  const failures = results.filter(r => r.status === 'rejected')

  if (failures.length > 0) {
    console.error('[VideoManager] Partial delete failure:', failures)

    // Log which operations failed
    const operationNames = ['video key', 'category set', 'all videos set']
    failures.forEach((failure, index) => {
      if (failure.status === 'rejected') {
        console.error(`[VideoManager] Failed to delete from ${operationNames[index]}:`, failure.reason)
      }
    })

    throw new Error(`Failed to delete video completely. ${failures.length}/${kvOperations.length} operations failed. Database may be inconsistent - run rebuild stats to fix.`)
  }

  console.log(`[VideoManager] Successfully deleted video ${videoId}`)
  return { deletedVectorIds }
}

/**
 * Get every video by paginating through videos:all until exhausted.
 * Used before destructive index rebuilds so videos beyond the first page
 * are never dropped from the indexes.
 */
export async function getAllVideosComplete(): Promise<Video[]> {
  const PAGE_SIZE = 500
  const all: Video[] = []
  let offset = 0

  // Paginate on the raw ID count from the zset, NOT the loaded video count.
  // getAllVideos drops IDs whose video:<id> record is missing, so a single
  // corrupt record would shorten a page and stop the loop early, silently
  // dropping every video after that offset. Reading IDs directly avoids that.
  while (true) {
    const ids = await kv.zrange('videos:all', offset, offset + PAGE_SIZE - 1, { rev: true })
    if (!ids || ids.length === 0) break

    for (const id of ids) {
      const video = await getVideo(id as string)
      if (video) all.push(video)
    }

    if (ids.length < PAGE_SIZE) break
    offset += PAGE_SIZE
  }

  return all
}

/**
 * Auto-rebuild Redis category sets from actual video data
 * Uses Redis lock to prevent concurrent rebuilds
 */
async function autoRebuildCategorySets(): Promise<boolean> {
  const LOCK_KEY = 'videos:rebuild-lock'
  const LOCK_TTL = 30 // 30 seconds timeout

  try {
    // Try to acquire lock (NX = only set if not exists, EX = expiry in seconds)
    const lockAcquired = await kv.set(LOCK_KEY, Date.now(), { nx: true, ex: LOCK_TTL })

    if (!lockAcquired) {
      console.log('[VideoManager] ⏭️ Rebuild already in progress, skipping...')
      return false
    }

    console.log('[VideoManager] 🔧 Auto-rebuilding category sets (lock acquired)...')

    // Get all videos from actual data (paginated so we never drop videos
    // beyond the first page before deleting the indexes)
    const allVideos = await getAllVideosComplete()
    console.log(`[VideoManager] Found ${allVideos.length} videos to rebuild`)

    if (allVideos.length === 0) {
      console.warn('[VideoManager] No videos found, skipping rebuild')
      await kv.del(LOCK_KEY)
      return false
    }

    // Clear existing category sets
    const categories: VideoCategory[] = ['Leadership', 'AI Works', 'Health', 'Entertaining', 'Human Philosophy']
    await Promise.all(categories.map(cat => kv.del(`videos:${cat}`)))

    // Rebuild category sets
    const categoryStats: Record<string, number> = {}
    for (const video of allVideos) {
      await kv.sadd(`videos:${video.category}`, video.id)
      categoryStats[video.category] = (categoryStats[video.category] || 0) + 1
    }

    // Rebuild videos:all sorted set
    await kv.del('videos:all')
    for (const video of allVideos) {
      await kv.zadd('videos:all', { score: video.addedAt, member: video.id })
    }

    console.log('[VideoManager] ✅ Auto-rebuild completed:', categoryStats)

    // Release lock
    await kv.del(LOCK_KEY)
    return true
  } catch (error) {
    console.error('[VideoManager] ❌ Auto-rebuild failed:', error)
    // Release lock on error
    await kv.del(LOCK_KEY).catch(() => {})
    return false
  }
}

/**
 * Get video statistics with automatic inconsistency detection and auto-repair
 */
export async function getVideoStats() {
  try {
    const [leadership, aiWorks, health, entertaining, philosophy, total] = await Promise.all([
      kv.scard('videos:Leadership'),
      kv.scard('videos:AI Works'),
      kv.scard('videos:Health'),
      kv.scard('videos:Entertaining'),
      kv.scard('videos:Human Philosophy'),
      kv.zcard('videos:all'),
    ])

    let stats = {
      leadership: leadership || 0,
      aiWorks: aiWorks || 0,
      health: health || 0,
      entertaining: entertaining || 0,
      philosophy: philosophy || 0,
      total: total || 0,
    }

    // Detect inconsistency: if category counts don't sum to total, Redis sets are out of sync
    const categorySum = stats.leadership + stats.aiWorks + stats.health + stats.entertaining + stats.philosophy

    if (categorySum !== stats.total && stats.total > 0) {
      console.warn(`[VideoManager] ⚠️ Inconsistency detected: category sum (${categorySum}) != total (${stats.total})`)
      console.warn('[VideoManager] 🔧 Triggering auto-rebuild...')

      // Auto-rebuild with lock protection
      const rebuilt = await autoRebuildCategorySets()

      if (rebuilt) {
        // Fetch fresh stats after successful rebuild
        const [newLeadership, newAiWorks, newHealth, newEntertaining, newPhilosophy, newTotal] = await Promise.all([
          kv.scard('videos:Leadership'),
          kv.scard('videos:AI Works'),
          kv.scard('videos:Health'),
          kv.scard('videos:Entertaining'),
          kv.scard('videos:Human Philosophy'),
          kv.zcard('videos:all'),
        ])

        stats = {
          leadership: newLeadership || 0,
          aiWorks: newAiWorks || 0,
          health: newHealth || 0,
          entertaining: newEntertaining || 0,
          philosophy: newPhilosophy || 0,
          total: newTotal || 0,
        }

        console.log('[VideoManager] ✅ Returned fresh stats after auto-rebuild:', stats)
      } else {
        console.log('[VideoManager] ⏳ Rebuild in progress or failed, returning stale stats')
      }
    }

    return stats
  } catch (error) {
    console.error('Failed to get video stats:', error)
    return {
      leadership: 0,
      aiWorks: 0,
      health: 0,
      entertaining: 0,
      philosophy: 0,
      total: 0,
    }
  }
}

/**
 * Batch import videos from URLs
 */
export interface BatchImportResult {
  success: number
  failed: number
  errors: Array<{ url: string; error: string }>
}

export async function batchImportVideos(
  urls: string[],
  category: VideoCategory,
  userEmail: string
): Promise<BatchImportResult> {
  const result: BatchImportResult = {
    success: 0,
    failed: 0,
    errors: [],
  }

  for (const url of urls) {
    try {
      const videoId = extractVideoId(url)
      if (!videoId) {
        result.failed++
        result.errors.push({ url, error: 'Invalid YouTube URL' })
        continue
      }

      // Check if already exists
      const existing = await getVideo(videoId)
      if (existing) {
        result.failed++
        result.errors.push({ url, error: 'Video already exists' })
        continue
      }

      // Get metadata
      const metadata = await getVideoMetadata(videoId)

      // Get transcript (optional), but persist an actionable ingestion state
      // instead of collapsing every upstream failure into an empty string.
      const transcriptResult = await getVideoTranscriptResult(videoId)
      const transcript = transcriptResult.ok
        ? transcriptResult.transcript
        : ''

      // Create video object with bilingual structure
      const video: Video = {
        id: videoId,
        videoId,
        channelTitle: metadata.channelTitle,
        publishedAt: metadata.publishedAt,
        thumbnailUrl: metadata.thumbnailUrl,
        duration: metadata.duration,
        category,
        // English content (from YouTube)
        en: {
          title: metadata.title,
          description: metadata.description,
          transcript: transcript || undefined,
          summary: undefined, // Will be generated later
        },
        // Vietnamese content (empty, to be translated)
        vi: {
          title: '',
          description: '',
          transcript: undefined,
          summary: undefined,
        },
        addedAt: Date.now(),
        addedBy: userEmail,
        transcriptStatus: transcriptResult.ok
          ? 'ready'
          : transcriptStatusFromFailure(transcriptResult.code),
        transcriptErrorCode: transcriptResult.ok
          ? undefined
          : transcriptResult.code,
        translationStatus: {
          viTranslated: false,
        },
      }

      await saveVideo(video)
      result.success++
    } catch (error: any) {
      result.failed++
      result.errors.push({ url, error: error.message || 'Unknown error' })
    }
  }

  return result
}
